name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  test:
    if: github.ref_type != 'tag'
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        zig-version: [0.15.1]

    runs-on: ${{ matrix.os }}

    name: Build and Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1

      - name: Run tests
        run: zig build test --summary all

  format-check:
    if: github.ref_type != 'tag'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: ${{ matrix.zig-version }}

      - name: Check formatting
        run: if [ -f zenvars.zig ]; then zig fmt --check zenvars.zig; else echo "No zenvars.zig"; fi

  lint:
    if: github.ref_type != 'tag'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1

      - name: Zig check
        run: zig build --summary all
