name: Unit Tests

on:
  push:
    branches:
     - main
  pull_request:
    branches:
     - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and Test
    if: github.event_name == 'push' && github.ref_type != 'tag'
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.14.0
      - run: zig build test
