name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    if: github.event_name == 'push' && github.ref_type != 'tag'
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        zig-version: [0.14.0]

    runs-on: ${{ matrix.os }}

    name: Build and Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup zig
        uses: mlugg/setup-zig@v2
        with:
          version: ${{ matrix.zig-version }}

      - name: Run tests
        run: zig build test --summary all

  format-check:
    if: github.event_name == 'push' && github.ref_type != 'tag'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.14.0

      - name: Check formatting
        run: zig fmt --check zenvars.zig

  lint:
    if: github.event_name == 'push' && github.ref_type != 'tag'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.14.0

      - name: Zig check
        run: zig build --summary all
